--테이블 제거
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE AGECODE CASCADE CONSTRAINTS;
 DROP TABLE OTT_CRAWLING CASCADE CONSTRAINTS;
 DROP TABLE BOXOFFICE CASCADE CONSTRAINTS;
 DROP TABLE MOVIE CASCADE CONSTRAINTS;
DROP TABLE MOVIE_MEMVIEWS CASCADE CONSTRAINTS;
DROP TABLE MOVIE_NONMEMVIEWS CASCADE CONSTRAINTS;
DROP TABLE MOVIE_KEYWORD CASCADE CONSTRAINTS;

--시퀀스 제거
-- DROP SEQUENCE ott_seq;
DROP SEQUENCE SEQ_MEMVIEWS;

--테이블 생성
-- 멤버
CREATE TABLE MEMBER (
    M_EMAIL	        VARCHAR2(50)		NULL,
    AGECODE         VARCHAR2(2)         NULL,
	M_PW	        VARCHAR2(100)		NULL,
    SOCAL_ID        VARCHAR2(50)        NULL,
	M_NAME	        VARCHAR2(30)		NULL,
	M_NICKNAME	    VARCHAR2(30)		NULL,
	M_GENDER	    VARCHAR2(10)		NULL,
	M_BIRTHDAY	    VARCHAR2(10)		NULL,
	ADMIN	        VARCHAR2(1)	        DEFAULT 'N'	NOT NULL,
	LOGIN_OK	    VARCHAR2(1)	        DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN MEMBER.M_EMAIL    IS '이메일';
COMMENT ON COLUMN MEMBER.AGECODE    IS '연령대코드';
COMMENT ON COLUMN MEMBER.M_PW       IS '비밀번호';
COMMENT ON COLUMN MEMBER.SOCAL_ID   IS '소셜아이디';
COMMENT ON COLUMN MEMBER.M_NAME     IS '이름';
COMMENT ON COLUMN MEMBER.M_NICKNAME IS '닉네임';
COMMENT ON COLUMN MEMBER.M_GENDER   IS '성별';
COMMENT ON COLUMN MEMBER.M_BIRTHDAY IS '생년월일';
COMMENT ON COLUMN MEMBER.ADMIN      IS '관리자여부';
COMMENT ON COLUMN MEMBER.LOGIN_OK   IS '로그인가능여부';

--테이블 생성
--무비
create table movie (
    ID	NUMBER generated always as identity primary key,
    MOVIEID	VARCHAR2(6 BYTE) unique,
    POSTERS	VARCHAR2(2000 BYTE),
    TITLE	VARCHAR2(160 BYTE),
    ACTORS	VARCHAR2(4000 BYTE),
    DIRECTOR	VARCHAR2(1018 BYTE),
    STAFFS	CLOB,
    COMPANY	VARCHAR2(150 BYTE),
    DISTRIBUTOR	VARCHAR2(300 BYTE),
    GENRE	VARCHAR2(100 BYTE),
    TYPE	VARCHAR2(100 BYTE),
    RUNTIME	VARCHAR2(4 BYTE),
    RATING	VARCHAR2(100 BYTE),
    NATION	VARCHAR2(100 BYTE),
    repRlsDate	VARCHAR2(10 BYTE),
    KEYWORDS	VARCHAR2(500 BYTE),
    COST VARCHAR2(100 BYTE),
    audiAcc VARCHAR2(100 BYTE),
    salesAcc VARCHAR2(100 BYTE),
    PLOT CLOB
);

COMMENT ON COLUMN MOVIE.MOVIEID IS 'KMDBID';
COMMENT ON COLUMN MOVIE.POSTERS IS '포스터이미지';
COMMENT ON COLUMN MOVIE.TITLE IS '영화명';
COMMENT ON COLUMN MOVIE.ACTORS IS '배우명';
COMMENT ON COLUMN MOVIE.DIRECTOR IS '감독명';
COMMENT ON COLUMN MOVIE.STAFFS IS '제작진';
COMMENT ON COLUMN MOVIE.DISTRIBUTOR IS '제작사';
COMMENT ON COLUMN MOVIE.COMPANY IS '배급사';
COMMENT ON COLUMN MOVIE.GENRE IS '장르';
COMMENT ON COLUMN MOVIE.TYPE IS '유형구분';
COMMENT ON COLUMN MOVIE.RUNTIME IS '상영시간';
COMMENT ON COLUMN MOVIE.RATING IS '관람기준';
COMMENT ON COLUMN MOVIE.NATION IS '제작국가';
COMMENT ON COLUMN MOVIE.repRlsDate IS '개봉일자';
COMMENT ON COLUMN MOVIE.KEYWORDS IS '키워드';
COMMENT ON COLUMN MOVIE.COST IS '제작비';
COMMENT ON COLUMN MOVIE.audiAcc IS '누적관람인원';
COMMENT ON COLUMN MOVIE.salesAcc IS '누적매출액';
COMMENT ON COLUMN MOVIE.PLOT IS '줄거리';

--alter table movie modify staffs CLOB;
--alter table movie modify company varchar2(150);
alter table movie modify DIRECTOR varchar2(1018);
alter table movie modify ACTORS varchar2(4000);
alter table movie modify DISTRIBUTOR varchar2(300);
alter table movie modify title varchar2(160);
alter table movie modify NATION varchar2(100);
alter table movie modify POSTERS varchar2(2000);
alter table movie modify RUNTIME varchar2(4);


-- 연령대 코드
CREATE TABLE AGECODE (
    AGECODE        VARCHAR2(2)          NOT NULL PRIMARY KEY,
    AGE_GROUP      VARCHAR2(6)          NOT NULL
);

COMMENT ON COLUMN AGECODE.AGECODE   IS '연령대코드';
COMMENT ON COLUMN AGECODE.AGE_GROUP IS '연령대';

-- 연령대 코드 삽입
INSERT INTO AGECODE VALUES('A0','0~9');
INSERT INTO AGECODE VALUES('A1','10~19');
INSERT INTO AGECODE VALUES('A2','20~29');
INSERT INTO AGECODE VALUES('A3','30~39');
INSERT INTO AGECODE VALUES('A4','40~49');
INSERT INTO AGECODE VALUES('A5','50~59');
INSERT INTO AGECODE VALUES('A6','60~69');
INSERT INTO AGECODE VALUES('A7','70~79');
INSERT INTO AGECODE VALUES('A8','80~89');
INSERT INTO AGECODE VALUES('A9','90~99');
commit;
--OTT 크롤링 정보 저장
CREATE TABLE OTT_CRAWLING (
	OTT_NUMBER	    NUMBER		        NOT NULL PRIMARY KEY,
	OTT_NAME	    VARCHAR2(12)		NOT NULL,
	OTT_MOVIERANK	NUMBER		        NOT NULL,
	OTT_MOVIENAME   VARCHAR2(150)		NOT NULL,
	OTT_DATE	    VARCHAR2(10)	    NOT NULL
);

COMMENT ON COLUMN OTT_CRAWLING.OTT_NUMBER    IS '오티티번호';
COMMENT ON COLUMN OTT_CRAWLING.OTT_NAME      IS 'OTT카테고리';
COMMENT ON COLUMN OTT_CRAWLING.OTT_MOVIERANK IS '영화순위';
COMMENT ON COLUMN OTT_CRAWLING.OTT_MOVIENAME IS '영화명';
COMMENT ON COLUMN OTT_CRAWLING.OTT_DATE      IS '크롤링된 날짜';

--박스오피스
CREATE TABLE BOXOFFICE (
	BOX_LEVEL	    NUMBER		        NULL,
	BOX_NAME	    VARCHAR2(100)		NULL,
	BOX_STARTDATE	VARCHAR2(10)		NULL,
	BOX_MONEY       VARCHAR2(20)		NULL,
	BOX_ALLMONEY	VARCHAR2(20)	    NULL,
    BOX_PEOPLE	    VARCHAR2(20)	    NULL,
    BOX_ALLPEOPLE	VARCHAR2(20)	    NULL,
    BOX_SCREEN	    VARCHAR2(10)	    NULL,
    BOX_SCREENCNT	VARCHAR2(10)	    NULL,
    BOX_DATE	    VARCHAR2(10)	    NULL
);

COMMENT ON COLUMN BOXOFFICE.BOX_LEVEL     IS '영화순위';
COMMENT ON COLUMN BOXOFFICE.BOX_NAME      IS '영화명';
COMMENT ON COLUMN BOXOFFICE.BOX_STARTDATE IS '영화개봉일';
COMMENT ON COLUMN BOXOFFICE.BOX_MONEY     IS '영화매출액';
COMMENT ON COLUMN BOXOFFICE.BOX_ALLMONEY  IS '영화누적매출액';
COMMENT ON COLUMN BOXOFFICE.BOX_PEOPLE    IS '영화관객수';
COMMENT ON COLUMN BOXOFFICE.BOX_ALLPEOPLE IS '영화누적관객수';
COMMENT ON COLUMN BOXOFFICE.BOX_SCREEN    IS '영화스크린수';
COMMENT ON COLUMN BOXOFFICE.BOX_SCREENCNT IS '영화상영횟수';
COMMENT ON COLUMN BOXOFFICE.BOX_DATE      IS '영화데이터뽑아온일자';

-- 회원 검색 기록
CREATE TABLE MOVIE_MEMVIEWS(
    VIEWS_ID                NUMBER          NOT NULL PRIMARY KEY,
    MOVIE_ID                VARCHAR2(6),
    AGE_CD                  VARCHAR2(2),
    GENDER                  VARCHAR2(10),
    CREATE_DATE           DATE
);

COMMENT ON COLUMN MOVIE_MEMVIEWS.VIEWS_ID IS '기본키생성';
COMMENT ON COLUMN MOVIE_MEMVIEWS.MOVIE_ID IS '영화아이디';
COMMENT ON COLUMN MOVIE_MEMVIEWS.AGE_CD IS '연령대코드';
COMMENT ON COLUMN MOVIE_MEMVIEWS.GENDER IS '성별';
COMMENT ON COLUMN MOVIE_MEMVIEWS.GENDER IS '조회일';

-- 비회원 검색 기록
CREATE TABLE MOVIE_NONMEMVIEWS(
    MOVIE_ID               VARCHAR2(6) NOT NULL PRIMARY KEY,
    VIEWS                    NUMBER
);

COMMENT ON COLUMN MOVIE_NONMEMVIEWS.MOVIE_ID IS '영화아이디';
COMMENT ON COLUMN MOVIE_NONMEMVIEWS.VIEWS IS '조회수';

-- 키워드 기록 테이블
CREATE TABLE MOVIE_KEYWORD(
    KEYWORD               VARCHAR2(100) NOT NULL PRIMARY KEY,
    VIEWS                     NUMBER
);

COMMENT ON COLUMN MOVIE_KEYWORD.KEYWORD    IS '키워드';
COMMENT ON COLUMN MOVIE_KEYWORD.VIEWS          IS '키워드카운트';


--시퀀스 생성
--OTT 크롤링 시퀀스 
CREATE SEQUENCE OTT_SEQ
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;

-- 멤버 검색 기록 시퀀스
CREATE SEQUENCE SEQ_MEMVIEWS 
	  NOMAXVALUE
	  INCREMENT BY 1
	  START WITH 1;

commit;
